pre-release-replacements = [
  {file="../README.md", search="krust-sitter = .*", replace="krust-sitter = \"{{version}}\""},
  {file="../README.md", search="krust-sitter-tool = .*", replace="krust-sitter-tool = \"{{version}}\""},
]

consolidate-commits = true
shared-version = true
